name: Lint
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Run linter
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.33.2
          args: --timeout=5m
        env:
          GOFLAGS: "-mod=readonly"
