name: Lint
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        version: v1.32
        env:
          GOFLAGS: "-mod=readonly"
