name: Linter Check
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-contrib/golangci-lint@v1
        env:
          GOFLAGS: "-mod=readonly"
        with:
          golangci_lint_version: v1.26.0
